name: Build and Upload Artifacts

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up MSBuild
              uses: microsoft/setup-msbuild@v1.0.2

            - name: Build project
              run: msbuild ./Wii3DSUSoundTool/Wii3DSUSoundTool.vcxproj /p:Configuration=Release

            - name: Upload build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: Wii3DSUSoundTool.exe
                  path: |
                      **/Release/*.exe
